# Generated by Django 5.1.3 on 2024-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('Product_quantity', models.IntegerField()),
                ('Product_rating', models.FloatField()),
                ('Product_Company_name', models.CharField(max_length=50)),
                ('Product_info', models.CharField(max_length=200)),
            ],
        ),
    ]
