# Generated by Django 5.1.3 on 2024-11-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_product_product_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='Product_price',
        ),
    ]
