# Generated by Django 5.1.1 on 2024-12-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_product_price_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
