# Generated by Django 5.1.1 on 2024-12-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_Company_name',
            new_name='product_company_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_info',
            new_name='product_info',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_rating',
            new_name='product_rating',
        ),
    ]
