# Generated by Django 5.1.1 on 2024-12-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_product_company_name_product_product_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
