# Generated by Django 5.1.1 on 2024-12-06 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_username', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')])),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mobile', models.IntegerField()),
                ('user_password', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(8, message='Field must be at least 5 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least 8 characters, including one uppercase letter, one number, and one special character.', regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#])[A-Za-z\\d@$!%*?&#]{8,}$')])),
                ('user_age', models.IntegerField()),
                ('user_role', models.CharField(max_length=25)),
                ('user_order', models.JSONField()),
                ('user_cart', models.JSONField()),
                ('user_slug', models.SlugField()),
            ],
        ),
    ]
