# Generated by Django 5.1.1 on 2024-12-06 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, message='Field must be at least 5 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least 8 characters, including one uppercase letter, one number, and one special character.', regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#])[A-Za-z\\d@$!%*?&#]{8,}$')]),
        ),
    ]
