# Generated by Django 5.1.1 on 2024-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_cart',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_order',
            field=models.JSONField(null=True),
        ),
    ]
