# Generated by Django 5.1.1 on 2024-12-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_user_user_cart_alter_user_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
