# Generated by Django 5.1.1 on 2024-12-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_user_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_Image',
            new_name='user_image',
        ),
    ]
