# Generated by Django 5.1.1 on 2024-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_rename_user_image_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
