# Generated by Django 5.1.3 on 2024-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_user_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
