# Generated by Django 5.1.3 on 2024-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
