# Generated by Django 5.1.3 on 2024-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_user_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.JSONField(null=True),
        ),
    ]
