# Generated by Django 5.1.3 on 2025-01-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_user_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_slug',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.JSONField(null=True),
        ),
    ]
