# Generated by Django 5.1.3 on 2025-01-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_user_user_slug_alter_user_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_address',
        ),
    ]
