# Generated by Django 5.1.3 on 2025-01-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_remove_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.JSONField(null=True),
        ),
    ]
