# Generated by Django 5.1.3 on 2025-01-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_user_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
