# Generated by Django 5.1.3 on 2025-01-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_user_address_blank_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
